name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📚 Documentation'
    label: 'documentation'
  - title: '🔒 Security'
    label: 'security'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'documentation'
  default: patch
template: |
  ## Changes

  $CHANGES
  
  ## Performance Metrics
  
  If this release includes performance improvements, benchmark results will be included below.
  
  ## Breaking Changes
  
  $CHANGES
  
  ## Contributors
  
  Thanks to all contributors who made this release possible! 🎉

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.github/*'
      - 'Makefile'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/feat/i'
      - '/feature/i'
  - label: 'performance'
    branch:
      - '/perf\/.+/'
      - '/performance\/.+/'
    title:
      - '/perf/i'
      - '/performance/i'
      - '/optimization/i'
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/*'
    title:
      - '/docs/i'
      - '/documentation/i'
  - label: 'test'
    files:
      - '*_test.go'
      - 'test/*'
    title:
      - '/test/i'
      - '/testing/i'
